name: Test and check

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Format, lint, and typecheck
        run: deno task check

      - name: Unit tests
        run: deno task test
